### ISSUE TITLE
HTTP request parsing issues

### ISSUE THREAD

**Issue by mmogilvi** [xedakini/replicator#4]
Although I haven't tried to exploit it, version 4 does not appear to have anything to protect against a GET request of the form "GET /../../../../../any/file/on/the/local/filesystem", especially if you are NOT using "--flat" mode.  Some clients may automatically simplify ".."s before sending the request, but replicator shouldn't count on that.  ( http://stackoverflow.com/questions/5951029/read-http-output-using-shell-bash-script )

Also, aren't http headers supposed to be case insensitive?  Version 4 code appears to be case sensitive.

Version 3 didn't seem to have either of these problems.

Tangent: These jumped out at me when I was attempting to develop a patch to minimize cache collisions in --flat mode if the client sends some extra headers, but I kind of lost heart in dealing with version 4 after seeing them.  If these are obvious, what less-obvious problems might exist?  See https://bugs.gentoo.org/show_bug.cgi?id=442874 .  On the other hand, in my superficial look, version 4 does look like it has the potential to ultimately be a cleaner internal design.

**Comment by xedakini** [comment]
These two items (path normalization; case-insensitive headers) should be fixed in the just released v4.0alpha4 code (https://github.com/xedakini/replicator/archive/v4.0alpha4.tar.gz).

This release also add support for the X-Unique-Cache-Name header, which hopefully supports the requirements of Gentoo bug #442874.
